---

- hosts: all     # beginning of a block/statement is going to start with the hyphen.
  become: true
  tasks:

    - name: install apache2 package
      apt:
        name: apache2
        state: absent

    - name: add php support for apache
      apt: 
        name: libapache2-mod-php
        state: absent
