- name: add ssh key for ansible
  tags: always
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBwPv0biduitKAYBMdHVGFemxx+2izmiD5pPeTKooQlo ansible"

- name: generate ssh_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
